
# ======================================================== #
#                      DATABASE                            #
# ======================================================== #
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/hikmet-cakir
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver


# ======================================================== #
#                   JPA / HIBERNATE                        #
# ======================================================== #
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# ======================================================== #
#                        REDIS                             #
# ======================================================== #
spring.redis.host=localhost
spring.redis.port-number=6379
spring.redis.expire-time-as-minute=10